# Session 16: RAGAS Evaluation with Cost Analysis

Compare an open-source Fireworks AI RAG pipeline against an OpenAI `gpt-4.1-mini` equivalent using:
- **RAGAS** metrics: context recall, faithfulness, factual correctness, answer relevancy
- **LangSmith** tracing: token usage and cost per query

## Prerequisites
- `.env` file with `OPENAI_API_KEY`, `FIREWORKS_API_KEY`, `LANGCHAIN_API_KEY`
- PDF data in `data/cat-health-guide.pdf`

## Task 1: Environment Setup

In [15]:
import os
from dotenv import load_dotenv

load_dotenv()

# Override project name so traces are grouped separately for this evaluation
os.environ["LANGSMITH_PROJECT"] = "Session16-RAG-Eval"

## Task 2: Build Two RAG Pipelines

We reuse `_build_rag_graph` from `app/rag.py`, passing different embedding and LLM models.

In [16]:
from langchain_openai import ChatOpenAI, OpenAIEmbeddings
from app.rag import _build_rag_graph

DATA_DIR = "data"

# Pipeline 1: Fireworks AI (open-source models)
fw_graph = _build_rag_graph(DATA_DIR)

# Pipeline 2: OpenAI
oai_embedding = OpenAIEmbeddings(model="text-embedding-3-small")
oai_llm = ChatOpenAI(model="gpt-4.1-mini")
oai_graph = _build_rag_graph(DATA_DIR, embedding_model=oai_embedding, generator_llm=oai_llm)

print("Both RAG pipelines built successfully.")

Both RAG pipelines built successfully.

### Sanity check

In [17]:
test_q = "What vaccinations do cats need?"

fw_resp = fw_graph.invoke({"question": test_q})
print("Fireworks:", fw_resp["response"][:200])

oai_resp = oai_graph.invoke({"question": test_q})
print("\nOpenAI:", oai_resp["response"][:200])

Fireworks: **Core feline vaccines (recommended for all cats)**
1. **Rabies** (the only vaccine required by law in many areas)
2. **Feline herpesvirus type 1 (FHV‑1)** – the cause of “cat flu”
3. **Feline c

OpenAI: Cats need core vaccines which include rabies virus, feline herpesvirus type 1 (FHV-1), feline calicivirus (FCV), and feline panleukopenia virus (FPV). Vaccination against feline leukemia virus (FeLV)

## Task 3: Synthetic Test Data Generation with RAGAS

Generate synthetic questions from the same PDF used by the RAG pipelines.

We use `generate_with_chunks` instead of `generate_with_langchain_docs` because this academic PDF
lacks clear section headers, causing RAGAS's `HeadlinesExtractor` → `HeadlineSplitter` pipeline to fail.
Pre-chunking bypasses that step while preserving the rest of the SDG pipeline (themes, NER, embeddings, similarity).

In [18]:
from langchain_community.document_loaders import DirectoryLoader, PyMuPDFLoader
from langchain_text_splitters import RecursiveCharacterTextSplitter
from ragas.llms import LangchainLLMWrapper
from ragas.embeddings import LangchainEmbeddingsWrapper
from ragas.testset import TestsetGenerator

# Load source documents
directory_loader = DirectoryLoader(DATA_DIR, glob="**/*.pdf", loader_cls=PyMuPDFLoader)
docs = directory_loader.load()
print(f"Loaded {len(docs)} document pages.")

# Pre-chunk documents
text_splitter = RecursiveCharacterTextSplitter(chunk_size=1000, chunk_overlap=100)
chunks = text_splitter.split_documents(docs)
print(f"Split into {len(chunks)} chunks.")

# SDG uses a separate model to avoid circularity
generator_llm = LangchainLLMWrapper(ChatOpenAI(model="gpt-4.1"))
generator_embeddings = LangchainEmbeddingsWrapper(OpenAIEmbeddings())

generator = TestsetGenerator(llm=generator_llm, embedding_model=generator_embeddings)
dataset = generator.generate_with_chunks(chunks=chunks, testset_size=10)

Loaded 22 document pages.
Split into 124 chunks.

/var/folders/r4/cqrwpld94ldc4rgfhq1fbx8h0000gn/T/ipykernel_48638/4203258798.py:18: DeprecationWarning: LangchainLLMWrapper is deprecated and will be removed in a future version. Use llm_factory instead: from openai import OpenAI; from ragas.llms import llm_factory; llm = llm_factory('gpt-4o-mini', client=OpenAI(api_key='...'))
  generator_llm = LangchainLLMWrapper(ChatOpenAI(model="gpt-4.1"))
/var/folders/r4/cqrwpld94ldc4rgfhq1fbx8h0000gn/T/ipykernel_48638/4203258798.py:19: DeprecationWarning: LangchainEmbeddingsWrapper is deprecated and will be removed in a future version. Use the modern embedding providers instead: embedding_factory('openai', model='text-embedding-3-small', client=openai_client) or from ragas.embeddings import OpenAIEmbeddings, GoogleEmbeddings, HuggingFaceEmbeddings
  generator_embeddings = LangchainEmbeddingsWrapper(OpenAIEmbeddings())

Applying SummaryExtractor:   0%|          | 0/124 [00:00<?, ?it/s]

Applying CustomNodeFilter:   0%|          | 0/124 [00:00<?, ?it/s]

Node 4fee697f-f53a-4430-a0f8-1dbb56f21bc7 does not have a summary. Skipping filtering.
Node e9f25944-87f0-45b4-b84d-f2d192bd84a0 does not have a summary. Skipping filtering.
Node 287ae989-73ff-4104-a72a-3d1eb44e24b2 does not have a summary. Skipping filtering.
Node a3ae8346-4642-4980-ac53-be9a480db4d0 does not have a summary. Skipping filtering.
Node 942cb7f3-43c4-49ed-9409-4855e0309f25 does not have a summary. Skipping filtering.
Node 2e92c944-98d4-4194-a65a-eb65070adcf0 does not have a summary. Skipping filtering.
Node 2542a58d-6657-40f2-822a-d59a938cbd14 does not have a summary. Skipping filtering.
Node 8ddecfd2-3fa8-4fa0-9c92-55c1fbaaefdf does not have a summary. Skipping filtering.
Node f48dd928-7523-46ff-9928-d12e6d213c17 does not have a summary. Skipping filtering.
Node ea013c40-4947-486a-9f99-f430ebbe531f does not have a summary. Skipping filtering.
Node d27ec921-7276-491b-ad21-c948d7acbcfd does not have a summary. Skipping filtering.
Node 8e08791f-0705-4ea1-9d9d-2bcf29503c32 does not have a summary. Skipping filtering.
Node d16cb46e-c9a7-4cfe-bca4-d966b92e4ec3 does not have a summary. Skipping filtering.
Node 138ebc00-0392-456a-b212-1b62ec19a031 does not have a summary. Skipping filtering.
Node c6354f93-6e44-4843-baba-1953ef12942c does not have a summary. Skipping filtering.
Node 7b6629b9-9ad2-4ce3-b549-d96bd768b3a2 does not have a summary. Skipping filtering.
Node 520af463-ba30-4e74-aaa8-aaaac96a979e does not have a summary. Skipping filtering.
Node f8e82ef1-73f4-45bc-b7b9-8266675eb72a does not have a summary. Skipping filtering.
Node 6104803e-1bc5-48db-9df1-ca10d50de234 does not have a summary. Skipping filtering.
Node 2af00003-c5e5-4d92-ad01-966a978cd12a does not have a summary. Skipping filtering.
Node 11787e6e-efd1-499e-992f-e648ca875c0c does not have a summary. Skipping filtering.
Node 00f15da9-5184-48c8-93cb-4e2895c3100a does not have a summary. Skipping filtering.
Node da7fd5b0-f4f4-4a8d-b4cb-5c8c56dc82bc does not have a summary. Skipping filtering.
Node 3faf1f66-0343-4068-90f0-53ca05d37ca2 does not have a summary. Skipping filtering.
Node 031bed05-3ec3-4e85-ac35-367f30f4f594 does not have a summary. Skipping filtering.
Node 5821accc-b116-430e-8161-336d7beaaaf6 does not have a summary. Skipping filtering.
Node e4a244da-cf7c-403c-99b0-a65633ef518b does not have a summary. Skipping filtering.
Node 8ff265d5-aafe-42d0-bee2-a768a4d14571 does not have a summary. Skipping filtering.
Node 55c334e4-de4e-40ba-8ea9-c37e779ddb9c does not have a summary. Skipping filtering.
Node d5443be5-bfa4-403d-9b20-5ee9de89e999 does not have a summary. Skipping filtering.
Node f2754d11-e212-4dab-85ec-a0d96a9b5758 does not have a summary. Skipping filtering.
Node 946d470c-1385-4e63-a36a-58a8565a595a does not have a summary. Skipping filtering.
Node 0a87633c-3c7b-42ed-996f-1a0536815260 does not have a summary. Skipping filtering.
Node 92d4b995-33d4-420a-bc8f-63c2abc07583 does not have a summary. Skipping filtering.
Node f5abf198-0073-4f84-8814-2814092ae87f does not have a summary. Skipping filtering.
Node 9d78b04a-abcb-4d55-ac7e-a54d3365525f does not have a summary. Skipping filtering.
Node 04853a92-3880-44c8-af10-95e557aa7ae6 does not have a summary. Skipping filtering.
Node d9dd0961-2fa0-4775-8424-43f6723b87f2 does not have a summary. Skipping filtering.
Node 0f896d88-ec91-4a55-b1c7-1b0e1fa1477d does not have a summary. Skipping filtering.
Node 31d85e5a-cd71-4def-a114-636547b1df4f does not have a summary. Skipping filtering.
Node a70f5937-8d27-47b6-8b68-6ff7a82f5a1b does not have a summary. Skipping filtering.
Node 1e9aaaae-75f3-41f6-9bb4-d2dea1132802 does not have a summary. Skipping filtering.
Node aa2f5926-e2f5-402f-8778-1193ca9c0f2e does not have a summary. Skipping filtering.
Node 2e2ec807-b561-4b83-aab7-55ccdf7af806 does not have a summary. Skipping filtering.
Node f7d6b58e-6ec4-4a49-a25b-283b832ec631 does not have a summary. Skipping filtering.
Node ec4e1f9a-bd5a-4ca4-9da9-4288d5f9e82a does not have a summary. Skipping filtering.
Node f2168f76-425c-4260-abc3-7f0f0eb81192 does not have a summary. Skipping filtering.
Node 3e5f7350-586a-4a0e-88f4-f9bd40f76700 does not have a summary. Skipping filtering.
Node a24f631e-a921-4de9-b425-5e7ad69ee436 does not have a summary. Skipping filtering.
Node cdf0d768-1a63-41ff-814f-a166f2380f29 does not have a summary. Skipping filtering.
Node a452c9fd-9ae4-444e-91c7-fc00644dc6a0 does not have a summary. Skipping filtering.
Node 0850c70d-7621-4639-8248-c8e28ebce7f7 does not have a summary. Skipping filtering.
Node 7562c74e-a50b-4b44-9be9-c3a4f2a54429 does not have a summary. Skipping filtering.
Node a1d2211b-41da-4f83-b33b-4cd344f1d250 does not have a summary. Skipping filtering.
Node 7ce67fc2-be85-4357-a3d8-f803b2116ef0 does not have a summary. Skipping filtering.
Node 0a7a0e84-adcc-4464-9aea-9c0a379b9258 does not have a summary. Skipping filtering.
Node b91efbe8-1274-4f5f-8879-30fa0a61cf27 does not have a summary. Skipping filtering.
Node 45220e57-1bd0-470b-bfc6-373e1a879def does not have a summary. Skipping filtering.
Node 96ff6971-5066-40ae-957a-ae0b6611182c does not have a summary. Skipping filtering.
Node 878979d3-90de-4397-b27d-51db8e7f2525 does not have a summary. Skipping filtering.
Node e5e9d56c-680b-4837-b842-75eca5703956 does not have a summary. Skipping filtering.
Node d7d76b0c-66a7-4dc6-904b-13655fd3e22f does not have a summary. Skipping filtering.
Node eaacbd87-f5ff-4bf3-b9c5-591d71749319 does not have a summary. Skipping filtering.
Node 89144a7e-6d02-4caf-8427-ed693bc70d70 does not have a summary. Skipping filtering.
Node 64255a54-d10c-473e-9212-ea025c57bec4 does not have a summary. Skipping filtering.
Node 287f0fd8-c605-4f52-9cbe-a4d74d22a75e does not have a summary. Skipping filtering.
Node 6931bc88-a55e-44e0-9f61-df022b9456d1 does not have a summary. Skipping filtering.
Node 3e02de0b-c364-44f3-ab8e-410d90f07923 does not have a summary. Skipping filtering.
Node 03252a2a-b95b-4099-bb05-8f2800508068 does not have a summary. Skipping filtering.
Node 41029e5c-4127-43d8-9dd5-ffb611c5097e does not have a summary. Skipping filtering.
Node acc4a324-4080-4c98-9309-5347a4b64b46 does not have a summary. Skipping filtering.
Node cbb767c0-b284-4d79-90fb-a0cdf1cded85 does not have a summary. Skipping filtering.
Node 84cd691e-ba54-4c3c-b806-7e8148ffcfa1 does not have a summary. Skipping filtering.
Node 5794e45c-ac63-49af-a8c1-bb9c08beda93 does not have a summary. Skipping filtering.
Node bc76b20e-845d-4e92-b633-d1c23658ff32 does not have a summary. Skipping filtering.
Node 1896c909-eeb7-4fc0-b788-0c7653e82356 does not have a summary. Skipping filtering.
Node 0cbabcf0-caa3-4e49-867c-ab822e197f23 does not have a summary. Skipping filtering.
Node 09b20b85-a82f-4b72-8cb6-763eaf095cef does not have a summary. Skipping filtering.
Node c3f095d1-187e-4b7e-893f-b464ff312b02 does not have a summary. Skipping filtering.
Node 0aa98c7f-c952-4f27-8961-10f7e22f2e2f does not have a summary. Skipping filtering.
Node 7bd947c3-978d-4516-a70c-96cce56e8246 does not have a summary. Skipping filtering.
Node 7ff169b1-b6fc-42df-aac7-964b65635364 does not have a summary. Skipping filtering.
Node cd03a73a-511d-4268-acde-e9826f908070 does not have a summary. Skipping filtering.
Node 68c9fff2-68bf-4e72-a81b-b93ae540f9de does not have a summary. Skipping filtering.
Node dcc3c86e-4bd5-4924-82f1-12fecc87fff3 does not have a summary. Skipping filtering.
Node 9d745b5d-4d56-4ef6-a021-1a2d303fa0a9 does not have a summary. Skipping filtering.
Node 9930ce31-d2d9-4400-b259-2b81fad93fe8 does not have a summary. Skipping filtering.
Node 027b585f-ec5d-49a8-b481-c71c5d5a38c7 does not have a summary. Skipping filtering.
Node 0d255a6f-50d5-497c-9129-acaa5b79f2e1 does not have a summary. Skipping filtering.
Node 28fec2c2-70f0-4eea-a5f7-68b341089258 does not have a summary. Skipping filtering.
Node 0d063029-3538-437a-8d99-5930625117af does not have a summary. Skipping filtering.
Node fea225c5-55ea-40bc-85f9-719ce801696e does not have a summary. Skipping filtering.
Node 1feab156-c61c-4b34-b910-6f402adf86a5 does not have a summary. Skipping filtering.
Node ccd2accf-1640-418e-a8f0-ae9fab1b4191 does not have a summary. Skipping filtering.
Node ba7ed7d4-a981-43f4-81d7-303d299d9002 does not have a summary. Skipping filtering.
Node fa5c7cc3-a96c-4eb1-90e3-bd423bab1507 does not have a summary. Skipping filtering.
Node 799251b9-40ef-4661-877f-8e570cf47871 does not have a summary. Skipping filtering.
Node 46b692d9-5d64-4fdb-bfcd-b515846f7d9c does not have a summary. Skipping filtering.
Node c81c33d9-a235-4c99-940e-0b07ad00e06b does not have a summary. Skipping filtering.
Node a50aaf28-fd15-466d-ab60-7fe52648bf12 does not have a summary. Skipping filtering.
Node 080d69b4-8b4c-4c01-a402-9627a8b36bd9 does not have a summary. Skipping filtering.
Node 8d4c9f6b-8ae5-4a8d-851a-e0805439201b does not have a summary. Skipping filtering.
Node 9290b5e2-2dc8-4a66-aab5-7e96f03c8827 does not have a summary. Skipping filtering.
Node 43ffc217-3810-4cbc-a928-62df856ae794 does not have a summary. Skipping filtering.
Node c12088cd-4d8c-4ef5-9b98-1c11bd7821af does not have a summary. Skipping filtering.
Node 76a67f66-2493-432c-a1fa-1fe8100215a4 does not have a summary. Skipping filtering.
Node cd35e849-038c-47a2-b402-01e28c20e45e does not have a summary. Skipping filtering.
Node 81b5eee2-6d28-4fe6-94fb-a026c48e63ef does not have a summary. Skipping filtering.
Node 872f8d06-33e1-451b-b2ba-cb97f3bb4fd9 does not have a summary. Skipping filtering.
Node 3d622c35-5389-4b1d-92e9-de4eb0fb4cf1 does not have a summary. Skipping filtering.
Node f45038a8-829e-4ad7-bebf-7af9ce6d32d0 does not have a summary. Skipping filtering.
Node 4bafff4c-23f9-4976-aa04-8b36ff9ec98f does not have a summary. Skipping filtering.
Node 03e6cd11-88e6-43fd-a311-fcd178f69560 does not have a summary. Skipping filtering.
Node 5e4595bb-2b2c-4ccd-8ec2-50e620d11d16 does not have a summary. Skipping filtering.
Node 2540896f-5877-49b8-bcac-77e3e7622da3 does not have a summary. Skipping filtering.
Node 20655862-8148-4367-a645-3753108561c4 does not have a summary. Skipping filtering.
Node 877a76e7-3105-4015-a77a-2d4e43791a87 does not have a summary. Skipping filtering.
Node f81a0a81-1c24-4f08-9625-fba56fef5105 does not have a summary. Skipping filtering.
Node c89ff05f-55c7-4015-b8e8-a9ae6eee00c7 does not have a summary. Skipping filtering.
Node 40835c1c-e827-44fe-82a5-ff64c7825539 does not have a summary. Skipping filtering.
Node d8b76c8f-d375-4f36-aa01-95b36fc66eda does not have a summary. Skipping filtering.
Node 169e95be-285b-4bf4-85a4-991c7ecea387 does not have a summary. Skipping filtering.
Node 5c0d9172-a747-4016-8878-84fabb5eeb78 does not have a summary. Skipping filtering.
Node 9b8aba54-77c5-4be2-9f48-0016d907e006 does not have a summary. Skipping filtering.

Applying EmbeddingExtractor:   0%|          | 0/124 [00:00<?, ?it/s]

Applying ThemesExtractor:   0%|          | 0/124 [00:00<?, ?it/s]

Applying NERExtractor:   0%|          | 0/124 [00:00<?, ?it/s]

Applying CosineSimilarityBuilder:   0%|          | 0/1 [00:00<?, ?it/s]

Applying OverlapScoreBuilder:   0%|          | 0/1 [00:00<?, ?it/s]

Generating personas:   0%|          | 0/3 [00:00<?, ?it/s]

Generating Scenarios:   0%|          | 0/3 [00:00<?, ?it/s]

Generating Samples:   0%|          | 0/12 [00:00<?, ?it/s]

In [19]:
dataset.to_pandas()

,user_input,reference_contexts,reference,persona_name,query_style,query_length,synthesizer_name
0,wut r the 2021 AAHA/AAFP Feline Life Stage Gui...,[VETERINARY PRACTICE GUIDELINES\n2021 AAHA/AAF...,The 2021 AAHA/AAFP Feline Life Stage Guideline...,Cat Owner and Caregiver,MISSPELLED,LONG,single_hop_specific_query_synthesizer
1,wat is oral helth for cats?,"[and senior) as well as an end-of-life stage, ...",Oral health is one of the most critical health...,Feline Welfare Consultant,MISSPELLED,SHORT,single_hop_specific_query_synthesizer
2,wut r the 2021 AAHA/AAFP Feline Life Stage Gui...,[medical history; behavior; risk assessment; e...,The 2021 AAHA/AAFP Feline Life Stage Guideline...,Cat Owner and Caregiver,MISSPELLED,SHORT,single_hop_specific_query_synthesizer
3,What does the abbreviation DER stand for in th...,"[course of treatment, or procedure. Variations...",DER stands for daily energy requirements.,Feline Welfare Consultant,PERFECT_GRAMMAR,MEDIUM,single_hop_specific_query_synthesizer
4,Why cat owners need biosecurity measures if fe...,[<1-hop>\n\npeople” resource.128 This informat...,Cat owners need biosecurity measures if feedin...,NaN,NaN,NaN,multi_hop_abstract_query_synthesizer
5,Howw doo enviromental stressors like exturnal ...,"[<1-hop>\n\n130. van Bree FPJ, Bokken GCAM, Mi...",Enviromental stressors such as exturnal animal...,NaN,NaN,NaN,multi_hop_abstract_query_synthesizer
6,How can environmental stressors such as extern...,[<1-hop>\n\nInvestigating Urine Marking\n· Whe...,"Environmental stressors like external animals,...",NaN,NaN,NaN,multi_hop_abstract_query_synthesizer
7,How can owner education help address issues re...,"[<1-hop>\n\nspace, administration at this loca...",Owner education plays a crucial role in addres...,NaN,NaN,NaN,multi_hop_abstract_query_synthesizer
8,how do i make sure my cat patient has less str...,[<1-hop>\n\nthe cat is reacting to the environ...,To make sure your cat patient has less stress ...,NaN,NaN,NaN,multi_hop_specific_query_synthesizer
9,wat r importnt health and behavor things to ch...,[<1-hop>\n\ndetection of changes and identiﬁca...,Important health and behavior things to check ...,NaN,NaN,NaN,multi_hop_specific_query_synthesizer
10,What vet recs is there for managing overweight...,"[<1-hop>\n\nclinical,\nclinicopathological\nch...",Vet recs for managing overweight cats include ...,NaN,NaN,NaN,multi_hop_specific_query_synthesizer
11,wat is Vet Clin North Am Small Anim Pract say ...,[<1-hop>\n\nDOI: 10.3390/ani9121105.\n79. Bufﬁ...,Vet Clin North Am Small Anim Pract discusses f...,NaN,NaN,NaN,multi_hop_specific_query_synthesizer

## Task 4: Run Both Pipelines on Test Data

In [22]:
import copy
import time
from openai import RateLimitError

# --- Fireworks pipeline (with retry for rate limits) ---
fw_dataset = copy.deepcopy(dataset)
for i, test_row in enumerate(fw_dataset):
    for attempt in range(3):
        try:
            response = fw_graph.invoke({"question": test_row.eval_sample.user_input})
            test_row.eval_sample.response = response["response"]
            test_row.eval_sample.retrieved_contexts = [ctx.page_content for ctx in response["context"]]
            print(f"  [{i+1}/{len(fw_dataset.samples)}] done")
            break
        except RateLimitError:
            wait = 30 * (attempt + 1)
            print(f"  [{i+1}/{len(fw_dataset.samples)}] rate limited, waiting {wait}s...")
            time.sleep(wait)
    time.sleep(15)

print("Fireworks pipeline done.")

  [1/12] done
  [2/12] done
  [3/12] done
  [4/12] done
  [5/12] done
  [6/12] done
  [7/12] done
  [8/12] done
  [9/12] done
  [10/12] done
  [11/12] done
  [12/12] done
Fireworks pipeline done.

In [23]:
# --- OpenAI pipeline ---
oai_dataset = copy.deepcopy(dataset)
for i, test_row in enumerate(oai_dataset):
    response = oai_graph.invoke({"question": test_row.eval_sample.user_input})
    test_row.eval_sample.response = response["response"]
    test_row.eval_sample.retrieved_contexts = [ctx.page_content for ctx in response["context"]]
    print(f"  [{i+1}/{len(oai_dataset.samples)}] done")

print("OpenAI pipeline done.")

  [1/12] done
  [2/12] done
  [3/12] done
  [4/12] done
  [5/12] done
  [6/12] done
  [7/12] done
  [8/12] done
  [9/12] done
  [10/12] done
  [11/12] done
  [12/12] done
OpenAI pipeline done.

## Task 5: RAGAS Evaluation

In [26]:
import numpy as np
from ragas import EvaluationDataset, evaluate, RunConfig
from ragas.metrics import LLMContextRecall, Faithfulness, FactualCorrectness, ResponseRelevancy

evaluator_llm = LangchainLLMWrapper(ChatOpenAI(model="gpt-4.1-mini"))
custom_run_config = RunConfig(timeout=360)
metrics = [LLMContextRecall(), Faithfulness(), FactualCorrectness(), ResponseRelevancy()]

fw_df = fw_dataset.to_pandas().replace({np.nan: None})
fw_eval_dataset = EvaluationDataset.from_pandas(fw_df)

fw_result = evaluate(
    dataset=fw_eval_dataset,
    metrics=metrics,
    llm=evaluator_llm,
    run_config=custom_run_config,
)
print("Fireworks RAGAS results:")
fw_result

/var/folders/r4/cqrwpld94ldc4rgfhq1fbx8h0000gn/T/ipykernel_48638/3523268500.py:3: DeprecationWarning: Importing LLMContextRecall from 'ragas.metrics' is deprecated and will be removed in v1.0. Please use 'ragas.metrics.collections' instead. Example: from ragas.metrics.collections import LLMContextRecall
  from ragas.metrics import LLMContextRecall, Faithfulness, FactualCorrectness, ResponseRelevancy
/var/folders/r4/cqrwpld94ldc4rgfhq1fbx8h0000gn/T/ipykernel_48638/3523268500.py:3: DeprecationWarning: Importing Faithfulness from 'ragas.metrics' is deprecated and will be removed in v1.0. Please use 'ragas.metrics.collections' instead. Example: from ragas.metrics.collections import Faithfulness
  from ragas.metrics import LLMContextRecall, Faithfulness, FactualCorrectness, ResponseRelevancy
/var/folders/r4/cqrwpld94ldc4rgfhq1fbx8h0000gn/T/ipykernel_48638/3523268500.py:3: DeprecationWarning: Importing FactualCorrectness from 'ragas.metrics' is deprecated and will be removed in v1.0. Please use 'ragas.metrics.collections' instead. Example: from ragas.metrics.collections import FactualCorrectness
  from ragas.metrics import LLMContextRecall, Faithfulness, FactualCorrectness, ResponseRelevancy
/var/folders/r4/cqrwpld94ldc4rgfhq1fbx8h0000gn/T/ipykernel_48638/3523268500.py:3: DeprecationWarning: Importing ResponseRelevancy from 'ragas.metrics' is deprecated and will be removed in v1.0. Please use 'ragas.metrics.collections' instead. Example: from ragas.metrics.collections import ResponseRelevancy
  from ragas.metrics import LLMContextRecall, Faithfulness, FactualCorrectness, ResponseRelevancy
/var/folders/r4/cqrwpld94ldc4rgfhq1fbx8h0000gn/T/ipykernel_48638/3523268500.py:5: DeprecationWarning: LangchainLLMWrapper is deprecated and will be removed in a future version. Use llm_factory instead: from openai import OpenAI; from ragas.llms import llm_factory; llm = llm_factory('gpt-4o-mini', client=OpenAI(api_key='...'))
  evaluator_llm = LangchainLLMWrapper(ChatOpenAI(model="gpt-4.1-mini"))

Evaluating:   0%|          | 0/48 [00:00<?, ?it/s]

LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.

Fireworks RAGAS results:

{'context_recall': 0.8653, 'faithfulness': 0.5501, 'factual_correctness(mode=f1)': 0.2625, 'answer_relevancy': 0.6907}

In [27]:
oai_df = oai_dataset.to_pandas().replace({np.nan: None})
oai_eval_dataset = EvaluationDataset.from_pandas(oai_df)

oai_result = evaluate(
    dataset=oai_eval_dataset,
    metrics=metrics,
    llm=evaluator_llm,
    run_config=custom_run_config,
)
print("OpenAI RAGAS results:")
oai_result

Evaluating:   0%|          | 0/48 [00:00<?, ?it/s]

LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.

OpenAI RAGAS results:

{'context_recall': 0.8653, 'faithfulness': 0.8947, 'factual_correctness(mode=f1)': 0.3658, 'answer_relevancy': 0.7840}

In [29]:
import pandas as pd

fw_scores = fw_result.to_pandas().select_dtypes(include="number").mean()
oai_scores = oai_result.to_pandas().select_dtypes(include="number").mean()

comparison = pd.DataFrame({
    "Fireworks (OSS)": fw_scores,
    "OpenAI (gpt-4.1-mini)": oai_scores,
})
comparison["Delta"] = comparison["OpenAI (gpt-4.1-mini)"] - comparison["Fireworks (OSS)"]
comparison

                              Fireworks (OSS)  OpenAI (gpt-4.1-mini)     Delta
context_recall                       0.865278               0.865278  0.000000
faithfulness                         0.550106               0.894685  0.344579
factual_correctness(mode=f1)         0.262500               0.365833  0.103333
answer_relevancy                     0.690654               0.784028  0.093374

## Task 6: LangSmith Evaluation with Cost Tracking

Upload the synthetic test data to a LangSmith dataset and run both pipelines through
`langsmith.evaluation.evaluate()` to capture per-query token usage and cost in the dashboard.

In [30]:
from uuid import uuid4
from langsmith import Client

ls_client = Client()

# Create a LangSmith dataset from our synthetic test data
ls_dataset_name = f"Session16-RAG-Eval-{uuid4().hex[:8]}"
ls_dataset = ls_client.create_dataset(ls_dataset_name, description="Synthetic test data for Session 16 RAG comparison")

test_df = dataset.to_pandas()
for _, row in test_df.iterrows():
    ls_client.create_example(
        inputs={"question": row["user_input"]},
        outputs={"reference": row["reference"]},
        dataset_id=ls_dataset.id,
    )

print(f"Created LangSmith dataset '{ls_dataset_name}' with {len(test_df)} examples.")

Created LangSmith dataset 'Session16-RAG-Eval-786e0ef6' with 12 examples.

### Define evaluators

In [33]:
from openevals.llm import create_llm_as_judge

# QA correctness
qa_evaluator = create_llm_as_judge(
    prompt="You are evaluating a QA system. Given the input, assess whether the prediction is correct.\n\nInput: {inputs}\nPrediction: {outputs}\nReference answer: {reference_outputs}\n\nIs the prediction correct? Return 1 if correct, 0 if incorrect.",
    feedback_key="qa",
    model="openai:gpt-4.1-mini",
)

# Labeled helpfulness
labeled_helpfulness_evaluator = create_llm_as_judge(
    prompt=(
        "You are assessing a submission based on the following criterion:\n\n"
        "helpfulness: Is this submission helpful to the user, "
        "taking into account the correct reference answer?\n\n"
        "Input: {inputs}\n"
        "Submission: {outputs}\n"
        "Reference answer: {reference_outputs}\n\n"
        "Does the submission meet the criterion? Return 1 if yes, 0 if no."
    ),
    feedback_key="helpfulness",
    model="openai:gpt-4.1-mini",
)

evaluators = [qa_evaluator, labeled_helpfulness_evaluator]

### Define target functions for each pipeline

In [34]:
def fw_target(inputs: dict) -> dict:
    """Run the Fireworks RAG pipeline."""
    result = fw_graph.invoke({"question": inputs["question"]})
    return {"output": result["response"]}

def oai_target(inputs: dict) -> dict:
    """Run the OpenAI RAG pipeline."""
    result = oai_graph.invoke({"question": inputs["question"]})
    return {"output": result["response"]}

### Run LangSmith evaluation for both pipelines

In [35]:
from langsmith.evaluation import evaluate as ls_evaluate

fw_ls_result = ls_evaluate(
    fw_target,
    data=ls_dataset_name,
    evaluators=evaluators,
    metadata={"revision_id": "fireworks_oss"},
)
print("Fireworks LangSmith evaluation complete.")

View the evaluation results for experiment: 'best-thumb-26' at:
https://smith.langchain.com/o/991456bb-c3e2-422e-957d-4e5bfe176b65/datasets/797ed67f-678f-4c25-b401-c9e24ccd97d7/compare?selectedSessions=2e10a5df-d116-465f-b6df-d08479dd313e

0it [00:00, ?it/s]

Fireworks LangSmith evaluation complete.

In [36]:
oai_ls_result = ls_evaluate(
    oai_target,
    data=ls_dataset_name,
    evaluators=evaluators,
    metadata={"revision_id": "openai_gpt41mini"},
)
print("OpenAI LangSmith evaluation complete.")

View the evaluation results for experiment: 'enchanted-rate-58' at:
https://smith.langchain.com/o/991456bb-c3e2-422e-957d-4e5bfe176b65/datasets/797ed67f-678f-4c25-b401-c9e24ccd97d7/compare?selectedSessions=8c509399-3f7d-479c-8983-b0372b3460ed

0it [00:00, ?it/s]

OpenAI LangSmith evaluation complete.

## Task 7: Analysis

### LangSmith Results

![LangSmith Evaluation Dashboard](langsmith.png)

### Combined Comparison

| Metric | Fireworks (OSS) | OpenAI (gpt-4.1-mini) | Delta |
|--------|----------------|----------------------|-------|
| **RAGAS: context_recall** | 0.8653 | 0.8653 | 0.0000 |
| **RAGAS: faithfulness** | 0.5501 | 0.8947 | +0.3446 |
| **RAGAS: factual_correctness** | 0.2625 | 0.3658 | +0.1033 |
| **RAGAS: answer_relevancy** | 0.6907 | 0.7840 | +0.0934 |
| **LangSmith: qa** | 0.67 | 0.75 | +0.08 |
| **LangSmith: helpfulness** | 0.75 | 0.83 | +0.08 |
| **LangSmith: P50 latency** | 5.18s | 2.85s | -2.33s |
| **LangSmith: P99 latency** | 13.23s | 5.81s | -7.42s |
| **LangSmith: cost** | ~$0.008 | ~$0.008 | ~$0.00 |

### Key Takeaways

1. **Context recall is identical** (0.8653) — both embedding models (Fireworks qwen3-embedding-8b vs OpenAI text-embedding-3-small) retrieve equally relevant context for this dataset.
2. **OpenAI outperforms on other RAG metrics** — OpenAI model leads on factual correctness, answer relevancy, QA correctness, and helpfulness, while Fireworks GPT OSS performs much worse, likely due to it hallucinates more
3. **OpenAI is ~2x faster at similar cost** — P50 latency is 2.85s vs 5.18s, and total cost is comparable. OpenAI is the clear winner here: better quality, faster response, and no meaningful cost penalty.